# 1 张量

TensorFlow是张量+计算图的意思

Tensorflow的基本数据结构是张量Tensor。张量即多维数组。Tensorflow的张量和numpy中的array很类似。



一些特殊的张量

- tf.Variable
- tf.constant
- tf.placeholder
- tf.SparseTensor

## 1.1 常量张量

tf.Tensor具有以下属性：
- 数据类型（float32, int32, string等）
- 形状

In [1]:
import numpy as np
import tensorflow as tf

i = tf.constant(1) # tf.int32 类型常量
l = tf.constant(1,dtype = tf.int64) # tf.int64 类型常量
f = tf.constant(1.23) #tf.float32 类型常量
d = tf.constant(3.14,dtype = tf.double) # tf.double 类型常量
s = tf.constant("hello world") # tf.string类型常量
b = tf.constant(True) #tf.bool类型常量

print(i)
print(l)
print(f)
print(d)
print(s)
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1.23, shape=(), dtype=float32)
tf.Tensor(3.14, shape=(), dtype=float64)
tf.Tensor(b'hello world', shape=(), dtype=string)
tf.Tensor(True, shape=(), dtype=bool)


In [2]:
print(tf.int64 == np.int64) 
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode) # tf.string类型和np.unicode类型不等价

True
True
True
False


### 1.1.1 Rank
rank是tf.Tensor对象的维度。类似于order,degree或ｎ维。

| rank	| 数学实体 |
| ---- | ---- |
| 0	| 标量（仅幅度） |
| 1	| 向量（大小和方向） |
| 2	| 矩阵（数字表） |
| 3	| 3维张量（数字的立方） |
| ñ	| n维张量 |


例如：

- 彩色图像有rgb三个通道，可以表示为3维张量。
- 视频还有时间维，可以表示为4维张量。

可以简单地总结为：有几层中括号，就是多少维的张量。

In [9]:
scalar = tf.constant(True)  #标量，0维张量

print(scalar)
print(tf.rank(scalar))
print(scalar.numpy().ndim)  # tf.rank的作用和numpy的ndim方法相同

tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(0, shape=(), dtype=int32)
0


In [10]:
vector = tf.constant([1.0,2.0,3.0,4.0]) #向量，1维张量

print(vector)
print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)
1


In [10]:
matrix = tf.constant([[1.0,2.0],[3.0,4.0]]) #矩阵, 2维张量

print(tf.rank(matrix).numpy())
print(np.ndim(matrix))

2
2


In [11]:
tensor3 = tf.constant([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])  # 3维张量
print(tensor3)
print(tf.rank(tensor3))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


### 1.1.2 数据类型
除维数外，张量还具有数据类型。

具有一个以上的数据类型是不可能的。但是，可以将任意数据结构序列化为strings并将其存储在tf.Tensors中。

可以使用tf.cast命令将tf.Tensors从一种数据类型转换为另一种数据类型：

In [12]:
h = tf.constant([123,456],dtype = tf.int32)
f = tf.cast(h,tf.float32)
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


可以用numpy方法将tensorflow中的张量转化成numpy中的张量。

可以用shape方法查看张量的尺寸。

In [16]:
y = tf.constant([[1.0,2.0],[3.0,4.0]])
print(y.numpy()) #转换成np.array
print(y.shape)

[[1. 2.]
 [3. 4.]]
(2, 2)


### 2.2 变量张量

模型中需要被训练的参数一般被设置成变量

In [17]:
# 常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0,2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0,1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
140308470652608
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
140308470808832


In [22]:
# 变量的值可以改变，可以通过assign, assign_add等方法给变量重新赋值
v = tf.Variable([1.0,2.0])
print(v)
print(id(v))
v.assign_add([1.0,1.0])
print(v)
print(id(v))
v = v + tf.Variable([1.0,2.0],name = "v")
print(v)
print(id(v))



<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
140308396667920
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
140308396667920
tf.Tensor([3. 5.], shape=(2,), dtype=float32)
140308471211648
